"""Cria modelos Usuario e Horario e adiciona campos

Revision ID: a61c9306332b
Revises: 
Create Date: 2025-11-13 09:42:29.502670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a61c9306332b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('dias_semana', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('horario_rega')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    op.create_table('horario_rega',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hora', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('duracao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dias_semana', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('horario_rega_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('horario_rega_pkey'))
    )
    op.drop_table('horario')
    # ### end Alembic commands ###
